### PR TITLE
Added void parameter checking

### PR DESCRIPTION
**Pull request by bdkuhman**
also my editor replaced all the tabs with spaces, because its probably a good idea to use spaces.

### CODE REVIEW

**Comment by DylanCirimelli-Low** [comment]
Thanks for adding this. I am going to change checking for "()" to a warning though since this is will cause an error to every void function call.

**Comment by bdkuhman** [comment]
it should. according to the "unofficially official style guide" all functions should have void in them if they don't take a parameter.

**Comment by bdkuhman** [comment]
OOOOR

**Comment by bdkuhman** [comment]
i think try to change it to "()\n{"
or add another one for "(){"

**Comment by bdkuhman** [comment]
Eventually I think I will try to change this over to regex if I can.

**Comment by DylanCirimelli-Low** [comment]
My understanding was that 

`int generateNumber(void)` requires "void" to be written, but something a function call like `number = generateNumber()` didn't. I'll go ahead and at it anyways though if you think that it best.

**Pull request merged**
